
$background = rgba(121315ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303032ff)

$inverse_primary = rgba(4b6077ff)

$inverse_surface = rgba(e3e2e4ff)

$on_background = rgba(e3e2e4ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(1c3247ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(051d31ff)

$on_primary_fixed_variant = rgba(34495eff)

$on_secondary = rgba(29313aff)

$on_secondary_container = rgba(d9e1edff)

$on_secondary_fixed = rgba(151c25ff)

$on_secondary_fixed_variant = rgba(404751ff)

$on_surface = rgba(e3e2e4ff)

$on_surface_variant = rgba(c3c6cdff)

$on_tertiary = rgba(422c0cff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(2a1800ff)

$on_tertiary_fixed_variant = rgba(5b4220ff)

$outline = rgba(8d9197ff)

$outline_variant = rgba(43474cff)

$primary = rgba(b3c9e3ff)

$primary_container = rgba(4d6279ff)

$primary_fixed = rgba(cfe5ffff)

$primary_fixed_dim = rgba(b3c9e3ff)

$scrim = rgba(000000ff)

$secondary = rgba(bfc7d3ff)

$secondary_container = rgba(404751ff)

$secondary_fixed = rgba(dbe3efff)

$secondary_fixed_dim = rgba(bfc7d3ff)

$shadow = rgba(000000ff)

$source_color = rgba(4d6279ff)

$surface = rgba(121315ff)

$surface_bright = rgba(38393bff)

$surface_container = rgba(1f2021ff)

$surface_container_high = rgba(292a2cff)

$surface_container_highest = rgba(343536ff)

$surface_container_low = rgba(1b1c1dff)

$surface_container_lowest = rgba(0d0e10ff)

$surface_dim = rgba(121315ff)

$surface_tint = rgba(b3c9e3ff)

$surface_variant = rgba(43474cff)

$tertiary = rgba(e5c095ff)

$tertiary_container = rgba(775b37ff)

$tertiary_fixed = rgba(ffddb6ff)

$tertiary_fixed_dim = rgba(e5c095ff)
