# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# Browser Picture in Picture
windowrule {
    name = tag-firefox-pip
    match:title = ^(Картинка в картинке)$
    tag = +pip
}

windowrule {
    name = firefox-pip-float
    match:tag = pip
    size = 530 300
    float = on
    no_initial_focus = true
    pin = on
    move = 1375 765
}

# Gnome Calendar
windowrule {
    name = tag-gnome-calendar
    match:title = ^(Календарь)$
    tag = +calendar
}

windowrule {
    name = gnome-calendar
    match:tag = calendar
    float = on
    pin = off
}

windowrule {
  name = obsidian-rule
  workspace = special:obsidian
  match:class = ^(obsidian)$
}

# idleinhibit
# windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen
