source = ~/.config/hypr/conf/windowrules/default.conf

windowrule = tile yes, match:title DeepSeek
windowrule = float yes, match:title (Системный монитор)
windowrule = float yes, match:title (Расширение: (Color Picker) - — Mozilla Firefox)
windowrule = float yes, match:title (Средство настройки Qt6)
